### ISSUE TITLE
"What's up Doc?"

### ISSUE THREAD

**Issue by jbenet** [ipfs/http-api-spec#1]
@RichardLitt how are the API docs coming along?

**Comment by jbenet** [comment]
Old discussion here: https://github.com/ipfs/go-ipfs/issues/785

**Comment by daviddias** [comment]
More threads with the same request:
- https://github.com/ipfs/go-ipfs/issues/1706
- https://github.com/ipfs/go-ipfs/issues/633
- https://github.com/ipfs/go-ipfs/issues/807
- https://github.com/ipfs/specs/issues/6

I made a comment, on https://github.com/ipfs/specs/issues/6#issuecomment-158766312

> I feel that the HTTP API should be treated as a spec (that code must follow) than trying to auto generate it from code (which will always miss to explain some of the design decisions)

This would help to guarantee consistency ( and would speed up things a bit vs trying to figure out one out of 1000 tools that can generate this stuff) 

//cc also interested @dignifiedquire @victorvictorbjelkholm

**Comment by dignifiedquire** [comment]
To be discussed at todays sync: https://public.etherpad-mozilla.org/p/nov-23-apps-on-ipfs

**Comment by RichardLitt** [comment]
At this point, they are going well -- I have the entire thing specced out in #13. All I need is more eyes on that and a better discussion about what to do about some things, like:
- adding `curl` commands to the description ([comment](https://github.com/ipfs/api/pull/13#discussion_r48444217));
- adding responses based on CLI responses when the working API doesn't have them yet (#14);
- what to do when the API is wrong (#14);
- how to split up the core from the other features, and whether we should document them all in this API on apiary. 

At this point, I think we should just merge it and fix it up as we go, but we do need to address these issues. 

Also, sorry about the delay.

**Comment by chrisvoncsefalvay** [comment]
Apiary documentation sounds a great idea.

Since not much has moved on this, I have started a fork and began to document it, shamelessly nicking the documentation from my own Python based IPFS client. Will I need to be added to the organisation to be able to do this properly? If so, please do.

**Comment by RichardLitt** [comment]
@chrisvoncsefalvay Not sure what you mean. I've merged 80% of the API, which is all done, in apiary format.

**Comment by RichardLitt** [comment]
Closing this issue as it is not actionable.
