### ISSUE TITLE
level 2 - rpc style json api 

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/http-api-spec#10]

**Comment by RichardLitt** [comment]
Can you give a bit more context than the title? I'm not sure what this issue means.

**Comment by daviddias** [comment]
What is level 1 and level 2 API spec? I guess my question is "why levels"?

**Comment by dignifiedquire** [comment]
Level 1 was discussed as being the transport agnostic variant, just as type signatures. And Level 2 would be the specific variant, on for `http` one for `cli` one for `json rpc`, etc.

**Comment by daviddias** [comment]
Got it, thank you for clarifying. The API specs were moved to ipfs/specs (as noted here https://github.com/ipfs/api/issues/11) and I've updated it here https://github.com/ipfs/specs/pull/65. Let's move the discussion over there.
