### ISSUE TITLE
Getting a Live Apiary mock daemon running

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/http-api-spec#103]
It would be good if we could run the mock tests on the [live site](http://docs.ipfs.apiary.io/). Currently, running the examples doesn't work because there isn't a daemon running - I think. 

I'm not sure how to go about doing this. @dignifiedquire Do you have any ideas? cc @diasdavid

**Comment by daviddias** [comment]
-> https://github.com/ipfs/http-api-spec/issues/23#issuecomment-174600741

**Comment by RichardLitt** [comment]
Closing in favor of #23.
