### ISSUE TITLE
Add `--resolve-type=false` flag to group `ls`

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/http-api-spec#105]
See https://github.com/ipfs/go-ipfs/pull/2824. 

Waiting on word from anyone on how to use a dash in the API:

```
$ curl -i "http://localhost:5001/api/v0/ls?arg=QmW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTQ?resolve-type=false"
```

Comes up as invalid. camelCase, nothing, and underscore also not working. @whyrusleeping any ideas?

**Comment by Kubuxu** [comment]
Can you try URL encoding the dash? It might be also bug in go-ipfs.

**Comment by RichardLitt** [comment]
Still fails. Possible bug?

**Comment by Kubuxu** [comment]
It works somehow with go-ipfs which uses http too. When I get home I will take a look at what is going on.

**Comment by Kubuxu** [comment]
You made a mistake in the HTTP request, it should have been `&` instead of second `?` near `resolve-type`.
