### ISSUE TITLE
Move the API specs into the Specs repo

### ISSUE THREAD

**Issue by daviddias** [ipfs/http-api-spec#11]
I'm wondering if there is any particular reason why this specs aren't on the Specs repo

**Comment by jbenet** [comment]
@diasdavid hmm good point. not sure, maybe because we made this repo with the intent to have the api live here? we can probably move stuff over to specs if you think it wold help to keep it all there

**Comment by jbenet** [comment]
yeah probably makes sense

**Comment by dignifiedquire** [comment]
I suggest moving the apiary spec from https://github.com/dignifiedquire/ipfs-http-api to here, and the spec documents into the specs repo

**Comment by jbenet** [comment]
Sgtm

**Comment by RichardLitt** [comment]
Sounds good to me, too. :+1: Happy to do this later today.

**Comment by daviddias** [comment]
Thank you :) Having specs on the specs repo helps for coordination (tagging PR and issues with its respective part of the system, so that others can tag along)

**Comment by dignifiedquire** [comment]
@RichardLitt I changed the apiary settings to pull from this repo

**Comment by daviddias** [comment]
@Dignifiedquire would it be possible for it to pull from ipfs/specs so that we have all the specs there?

**Comment by dignifiedquire** [comment]
@diasdavid it would but that would mean the file has to be in the top level and you can't nest it.

**Comment by daviddias** [comment]
@Dignifiedquire just one file right? I would be comfortable with that. Maybe we can contact support from Apiary to see if they would be open to add nesting as a feature

**Comment by RichardLitt** [comment]
Well, it may be smart to have both; the spec API, also listed in .apib, and then the _actual_ API, which could be listed here as functions that we know are currently available. This would solve some issues, like #14. This would allow us to look at specs when we want to know how the API should look, and to compare the two. The only real issue I can foresee with this is when we want to change both specs and the api here, but I don't think that's something that can be avoided. 

What do you think? I'll contact Apiary about nesting as a feature, if this sounds good.

**Comment by daviddias** [comment]
Having both sounds good :) Let's move it to the specs repo :D 

@dborzov found that you had invested some energy on documenting the CLI API as well (https://github.com/ipfs/go-ipfs/issues/785), wanna help us finish this endeavour, having the API spec'ed out will be incredibly helpful for everyone consuming IPFS with clients or simply building the client libraries (like js-ipfs-api)

**Comment by daviddias** [comment]
Apparently was done on:

https://github.com/ipfs/api/commit/098850538a469a7107671cba0982ba78095d4278

Thank you @RichardLitt

**Comment by RichardLitt** [comment]
Yep. Thanks.
