### ISSUE TITLE
http-api-spec tests

### ISSUE THREAD

**Issue by daviddias** [ipfs/http-api-spec#113]
From: https://github.com/ipfs/interface-ipfs-core/pull/44#issuecomment-237843777

> It would actually be good if https://github.com/ipfs/http-api-spec would have a battery of tests that could be used to test the API, so that we could run them against go-ipfs and js-ipfs. @whyrusleeping how interesting would it be to you to have the CLI extracted from go-ipfs, so that it can be compiled as a standalone binary so that we can put the shardness tests available to run against any IPFS implementation? (Might be better to talk about this in the http-api-spec repo)

**Comment by daviddias** [comment]
Related:
- https://github.com/ipfs/http-api-spec/issues/103
- https://github.com/ipfs/http-api-spec/issues/28
- https://github.com/ipfs/http-api-spec/issues/23

**Comment by RichardLitt** [comment]
Closing in favor of #23.
