### ISSUE TITLE
Prioritise certain endpoints

### ISSUE THREAD

**Issue by daviddias** [ipfs/http-api-spec#20]
Prioritising helps because it means js-ipfs gets a specs to follow as it needs. Right now these are:
- [x] block
- [x] bootstrap
- [ ] config
- [x] id
- [x] version

**Comment by daviddias** [comment]
Thank you @RichardLitt for shipping all of these, next one to be prioritised is `ipfs object` of 0.4.0 (which has extra methods)

**Comment by RichardLitt** [comment]
Well, they're not shipped yet. But I'll do object next. We still need to go through and merge them.
