### ISSUE TITLE
How do you get a mime-type of a request?

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/http-api-spec#21]
#### What

Apiary asks me to supply the mime-type of a request, as well as of a response. Here is an example:

```

+ Request Single File (application/json)

    #### Curl

        curl -F "file=test" http://localhost:5001/api/v0/add

+ Response 200 (application/json)
```

How do I get the mime-type of the Request? The response I can get from using the `-i` flag in curl. 

Brought up in https://github.com/ipfs/api/pull/17.

**Comment by RichardLitt** [comment]
You use Waveshark.

**Comment by daviddias** [comment]
Wireshark \* :D

**Comment by dignifiedquire** [comment]
What's Waveshark? where can I get some :)

**Comment by RichardLitt** [comment]
Hahah. Wireshark.

**Comment by jbenet** [comment]
[careful when surfing the web with wave sharks](https://www.youtube.com/watch?v=anhRxIQutZ8)

**Comment by RichardLitt** [comment]
ahaha
