### ISSUE TITLE
Arrange groupings semantically and not alphabetically

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/http-api-spec#22]
#### What

@diasdavid:

> @RichardLitt can we break the apiary API docs description using the same categories found on https://github.com/ipfs/specs/blob/ipfs/api/api/core/README.md ?

The suggestion is that we should have Network, Tooling, Extensions, and Core sections, and list each method in each section appropriately, instead of the alphabetical grab-bag we currently have.
#### Response

I'm not sure. I think that keeping it as it currently is OK. I also don't see a way in the apiary docs to do this easily. I think we should look into this again, after we have the API stubbed out.

**Comment by ralphtheninja** [comment]
> The suggestion is that we should have Network, Tooling, Extensions, and Core sections, and list each method in each section appropriately, instead of the alphabetical grab-bag we currently have.

+1

**Comment by RichardLitt** [comment]
@diasdavid How would you feel about a compromise, where I include a link to the spec for each command , and mention which group it is in in the description?

**Comment by RichardLitt** [comment]
@diasdavid Thoughts?

**Comment by daviddias** [comment]
Why do we need a compromise? Is there any technical limiting factor?

**Comment by RichardLitt** [comment]
I don't know of a way to do that easily in Apiary - sections aren't a thing, I think? I could do `# group tools` or something.
