### ISSUE TITLE
API tests - Auto generate API tests from the documentation + factor out sharness tests, making them available to be run against any IPFS implementation

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/http-api-spec#23]
So, now that we have at least _one_ of the IPFS methods logged using the Apiary format, we should think about adding sharness testing for the curl commands we log in the description field. Take a look at `apiary.apib` and grep for curl: you'll see the commands there, with the Body and Header in the response. 

There might be a way to automate this with apiary; if not, we should run it with sharness. I don't know fully how this would work yet. 

cc @jbenet @chriscool

**Comment by dignifiedquire** [comment]
@RichardLitt we talked about this, use [dredd](https://github.com/apiaryio/dredd) it generates tests from the apiary docs.

**Comment by RichardLitt** [comment]
> It would be good if we could run the mock tests on the live site. Currently, running the examples doesn't work because there isn't a daemon running - I think.

**Comment by RichardLitt** [comment]
@diasdavid, from: https://github.com/ipfs/interface-ipfs-core/pull/44#issuecomment-237843777

> It would actually be good if https://github.com/ipfs/http-api-spec would have a battery of tests that could be used to test the API, so that we could run them against go-ipfs and js-ipfs. @whyrusleeping how interesting would it be to you to have the CLI extracted from go-ipfs, so that it can be compiled as a standalone binary so that we can put the shardness tests available to run against any IPFS implementation? (Might be better to talk about this in the http-api-spec repo)

**Comment by jbenet** [comment]
+1 to dredd
