### ISSUE TITLE
[docs] List all existing API functionality in markdown

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/http-api-spec#4]
- [ ] level 2 - cli
- [ ] level 2 - http see #7

**Comment by RichardLitt** [comment]
These are now all documented in #13, and the level documentation has moved to https://github.com/ipfs/specs/tree/master/api. Ought we to close this, or reopen it in ipfs/specs, where we would need to fill out the CLI and HTTP docs for transport-specific methods?

**Comment by daviddias** [comment]
As pointed on https://github.com/ipfs/go-ipfs/issues/2165, go-ipfs HTTP API is accepting all methods in all endpoints, this creates space for some security holes (doing operations on GET that can bypass CORS protection.

**Comment by daviddias** [comment]
for reference: 
- core (programmatic interface) - https://github.com/ipfs/specs/pull/65/files
- http-api - inside this repo
- cli - https://github.com/ipfs/specs/pull/65/files

**Comment by RichardLitt** [comment]
I think we can close this, @diasdavid. I don't see that the original purpose is needed anymore.
