### ISSUE TITLE
Group `files`

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/http-api-spec#57]
This doesn't appear to be in the list of commands I had prefilled in the master branch of apiary.apib. But it ought to be in the API, right? Just checking before I do it in case there was a reason it wasn't there.

**Comment by whyrusleeping** [comment]
nope, the files command is good. you probably ran it against master before 0.4.0 dropped

**Comment by RichardLitt** [comment]
@whyrusleeping Cool. I will PR that, then.

**Comment by RichardLitt** [comment]
Closed with https://github.com/ipfs/http-api-spec/pull/58 opening.
