### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by daviddias** [ipfs/http-api-spec#70]
It would be good to have a clear understanding of how the http-api will evolve and how we will use the http-api-spec to achieve it, things we have talked so far:
- bikeshed each API group through a PR and then open issues for enhancement on go-ipfs and js-ipfs
- identify the clear problems with a current API (which are not design, but implementation problems) and fix them ASAP on go-ipfs, e.g: The fact that the API accepts any method, meaning that there is no CSRF protection possible.

**Comment by RichardLitt** [comment]
So, bikeshedding AFAIK is done. We've gone through each API group. It took a while. 

Identifying clear problems is not done. We've opened some issues: #61, #69. More to do. Any Method is a very valid concern. 

What I would like to do is to look at another API that people like for a _similar tool_ and see if there are any major things I can learn and integrate into this.
