### ISSUE TITLE
api commands bucketing

### ISSUE THREAD

**Issue by jbenet** [ipfs/http-api-spec#8]
### ipfs core -- required

ipfs version

ipfs node id
ipfs node start
ipfs node stop

ipfs block
ipfs block get
ipfs block put
ipfs block stat

ipfs object - Basic manipulation of the DAG
ipfs object data
ipfs object get
ipfs object links
ipfs object new
ipfs object patch
ipfs object put
ipfs object stat

ipfs refs - Listing of references. (Essentially, walking around the graph).
ipfs refs local

ipfs repo - Basic manipulation of the repo
ipfs repo init
ipfs repo stat
ipfs repo gc
ipfs repo config get
ipfs repo config put

ipfs pin - Basic manipulation of the pin set
ipfs pin add
ipfs pin ls
ipfs pin rm

ipfs log
ipfs log level
ipfs log tail

ipfs name (ipns)
ipfs name
ipfs name publish
ipfs name resolve
### ipfs ext - optional extensions

ipfs dns

ipfs resolve

ipfs tar
ipfs tar add
ipfs tar cat

ipfs tour

ipfs tour list
ipfs tour next
ipfs tour restart

ipfs files add
ipfs files cat
ipfs files get

ipfs stat - Statistics about everything
ipfs stats
ipfs stats bw

ipfs mount

ipfs bootstrap
ipfs bootstrap add
ipfs bootstrap list
ipfs bootstrap rm
### ipfs tool

ipfs commands
ipfs update
ipfs init - sugar around ipfs repo init

ipfs config
ipfs config edit
ipfs config replace
ipfs config show

ipfs daemon

ipfs diag
ipfs diag net
ipfs diag sys
### libp2p

ipfs ping

ipfs dht
ipfs dht findpeer
ipfs dht findprovs
ipfs dht get
ipfs dht put
ipfs dht query

ipfs swarm
ipfs swarm addrs
ipfs swarm addrs local
ipfs swarm connect
ipfs swarm disconnect
ipfs swarm filters
ipfs swarm filters add
ipfs swarm filters rm
ipfs swarm peers

ipfs record (iprs)
ipfs record put
ipfs record get

ipfs bitswap
ipfs bitswap stat
ipfs bitswap unwant
ipfs bitswap wantlist

**Comment by RichardLitt** [comment]
Closed in #9.
