### ISSUE TITLE
Apiary default font

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/http-api-spec#85]
Can it be smaller? Check with apiary.

**Comment by RichardLitt** [comment]
I do not think this is possible. Looks like we're locked in, at least on the apiary server. If we host it locally or on IPFS (which we should do?) we may be able to shrink it down.

**Comment by dignifiedquire** [comment]
Just use browser zoom?

We would lose a lot if we moved away from their hosting

**Comment by RichardLitt** [comment]
Closing this.

**Comment by Kubuxu** [comment]
Or use `stylish`.
